[package]
name = "cubecl-snake"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.24.0"
cubecl = { version = "0.7.0", features = ["cuda"] }
minifb = "0.28.0"
pollster = "0.4.0"
rand = "0.9.2"
